"""Adiciona crm.tickets e refatora status para Enums Nativos (PATTERN-002)

Revision ID: 8c18d11615bb
Revises: 66e5143a0b21
Create Date: 2025-11-05 16:48:02.116957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c18d11615bb'
down_revision: Union[str, Sequence[str], None] = '66e5143a0b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Criação dos enums nativos no PostgreSQL com schemas específicos
    op.execute("CREATE TYPE ai.ingestionstatus AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')")
    op.execute("CREATE TYPE crm.consenttype AS ENUM ('LGPD_V1', 'TERMS_OF_SERVICE')")
    op.execute("CREATE TYPE crm.ticketstatus AS ENUM ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')")
    
    # Criação da nova tabela tickets
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus', schema='crm', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['crm.clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crm'
    )
    
    # Alteração das colunas para usar os tipos ENUM
    op.alter_column('ingestion_queue', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ingestionstatus', schema='ai', create_type=False),
               existing_nullable=False,
               schema='ai',
               postgresql_using='status::ai.ingestionstatus')
               
    op.alter_column('consents', 'consent_type',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('LGPD_V1', 'TERMS_OF_SERVICE', name='consenttype', schema='crm', create_type=False),
               existing_nullable=False,
               schema='crm',
               postgresql_using='consent_type::crm.consenttype')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consents', 'consent_type',
               existing_type=postgresql.ENUM('LGPD_V1', 'TERMS_OF_SERVICE', name='consenttype', schema='crm'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='crm')
    op.alter_column('ingestion_queue', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ingestionstatus', schema='ai'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               schema='ai')
    op.drop_table('tickets', schema='crm')
    sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ingestionstatus', schema='ai').drop(op.get_bind())
    sa.Enum('LGPD_V1', 'TERMS_OF_SERVICE', name='consenttype', schema='crm').drop(op.get_bind())
    sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus', schema='crm').drop(op.get_bind())
    # ### end Alembic commands ###
