"""Sincroniza models com BD existente (ingestion_queue, rag_docs_1536)

Revision ID: c6fdf5d47d68
Revises: e325fe9953e1
Create Date: 2025-11-04 10:06:13.248549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6fdf5d47d68'
down_revision: Union[str, Sequence[str], None] = 'e325fe9953e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
